In [1]:
import pandas as pd
data=pd.read_csv("Churn_Modelling.csv")

In [2]:
data

,RowNumber,CustomerId,Surname,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited
0,1,15634602,Hargrave,619,France,Female,42,2,0.00,1,1,1,101348.88,1
1,2,15647311,Hill,608,Spain,Female,41,1,83807.86,1,0,1,112542.58,0
2,3,15619304,Onio,502,France,Female,42,8,159660.80,3,1,0,113931.57,1
3,4,15701354,Boni,699,France,Female,39,1,0.00,2,0,0,93826.63,0
4,5,15737888,Mitchell,850,Spain,Female,43,2,125510.82,1,1,1,79084.10,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9995,9996,15606229,Obijiaku,771,France,Male,39,5,0.00,2,1,0,96270.64,0
9996,9997,15569892,Johnstone,516,France,Male,35,10,57369.61,1,1,1,101699.77,0
9997,9998,15584532,Liu,709,France,Female,36,7,0.00,1,0,1,42085.58,1
9998,9999,15682355,Sabbatini,772,Germany,Male,42,3,75075.31,2,1,0,92888.52,1
9999,10000,15628319,Walker,792,France,Female,28,4,130142.79,1,1,0,38190.78,0

In [3]:
data=data.drop(columns=['RowNumber','CustomerId','Surname'],axis=1)

In [4]:
data.head()

,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited
0,619,France,Female,42,2,0.00,1,1,1,101348.88,1
1,608,Spain,Female,41,1,83807.86,1,0,1,112542.58,0
2,502,France,Female,42,8,159660.80,3,1,0,113931.57,1
3,699,France,Female,39,1,0.00,2,0,0,93826.63,0
4,850,Spain,Female,43,2,125510.82,1,1,1,79084.10,0

In [5]:
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder,StandardScaler,OneHotEncoder

label_encoder_gender=LabelEncoder()
data['Gender']=label_encoder_gender.fit_transform(data['Gender'])

In [6]:
onehot_encoder_geography=OneHotEncoder()
geo_encoder=onehot_encoder_geography.fit_transform(data[['Geography']])

In [7]:
geo_encoder=geo_encoder.toarray()

In [8]:
geo_encoder=pd.DataFrame(geo_encoder,columns=onehot_encoder_geography.get_feature_names_out(['Geography']))

In [9]:
data

,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited
0,619,France,0,42,2,0.00,1,1,1,101348.88,1
1,608,Spain,0,41,1,83807.86,1,0,1,112542.58,0
2,502,France,0,42,8,159660.80,3,1,0,113931.57,1
3,699,France,0,39,1,0.00,2,0,0,93826.63,0
4,850,Spain,0,43,2,125510.82,1,1,1,79084.10,0
...,...,...,...,...,...,...,...,...,...,...,...
9995,771,France,1,39,5,0.00,2,1,0,96270.64,0
9996,516,France,1,35,10,57369.61,1,1,1,101699.77,0
9997,709,France,0,36,7,0.00,1,0,1,42085.58,1
9998,772,Germany,1,42,3,75075.31,2,1,0,92888.52,1
9999,792,France,0,28,4,130142.79,1,1,0,38190.78,0

In [10]:
data=pd.concat([data.drop(columns=['Geography'],axis=1),geo_encoder],axis=1)

In [11]:
data

,CreditScore,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited,Geography_France,Geography_Germany,Geography_Spain
0,619,0,42,2,0.00,1,1,1,101348.88,1,1.0,0.0,0.0
1,608,0,41,1,83807.86,1,0,1,112542.58,0,0.0,0.0,1.0
2,502,0,42,8,159660.80,3,1,0,113931.57,1,1.0,0.0,0.0
3,699,0,39,1,0.00,2,0,0,93826.63,0,1.0,0.0,0.0
4,850,0,43,2,125510.82,1,1,1,79084.10,0,0.0,0.0,1.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...
9995,771,1,39,5,0.00,2,1,0,96270.64,0,1.0,0.0,0.0
9996,516,1,35,10,57369.61,1,1,1,101699.77,0,1.0,0.0,0.0
9997,709,0,36,7,0.00,1,0,1,42085.58,1,1.0,0.0,0.0
9998,772,1,42,3,75075.31,2,1,0,92888.52,1,0.0,1.0,0.0
9999,792,0,28,4,130142.79,1,1,0,38190.78,0,1.0,0.0,0.0

In [12]:
X=data.drop('EstimatedSalary',axis=1)
y=data['EstimatedSalary']

In [13]:
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.2,random_state=42)

In [14]:
scaler=StandardScaler()
X_train=scaler.fit_transform(X_train)
X_test=scaler.fit_transform(X_test)

In [15]:
import pickle

with open('label_encoder_gender.pkl','wb') as file:
    pickle.dump(label_encoder_gender,file)

with open('onehot_encoder_geo','wb') as file:
    pickle.dump(onehot_encoder_geography,file)

with open('scaler.pkl','wb') as file:
    pickle.dump(scaler,file)

In [19]:
X_train.shape[1]

12

In [17]:
import tensorflow as tf
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense

In [24]:
model=Sequential([
    Dense(64,activation='relu',input_shape=(X_train.shape[1],)),
    Dense(16,activation='relu'),
    Dense(1) #for regression we use linear activation function which is bydefault we not need to assign it 
]
)

d:\ANN_Classification\.venv\Lib\site-packages\keras\src\layers\core\dense.py:92: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)

In [25]:
model.compile(optimizer='adam',loss='mean_squared_error',metrics=['mse'])

In [27]:
model.summary()

Model: "sequential"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ dense_3 (Dense)                 │ (None, 64)             │           832 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_4 (Dense)                 │ (None, 16)             │         1,040 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_5 (Dense)                 │ (None, 1)              │            17 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 1,889 (7.38 KB)

 Trainable params: 1,889 (7.38 KB)

 Non-trainable params: 0 (0.00 B)

In [28]:
from tensorflow.keras.callbacks import EarlyStopping,TensorBoard
import datetime

In [29]:
logs_dir="Regression/logs/fit/"+datetime.datetime.now().strftime('%d%m%Y_%H%M%S')
tensorboard_callback=TensorBoard(logs_dir,histogram_freq=1)

In [30]:
earlystopping_callback=EarlyStopping(monitor='val_loss',patience=10,restore_best_weights=True)

In [35]:
history=model.fit(
    X_train,y_train,
    validation_data=(X_test,y_test),
    epochs=100,
    callbacks=[earlystopping_callback,tensorboard_callback]
)

Epoch 1/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 2s 5ms/step - loss: 13388164096.0000 - mse: 13388164096.0000 - val_loss: 13024496640.0000 - val_mse: 13024496640.0000
Epoch 2/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 13304235008.0000 - mse: 13304235008.0000 - val_loss: 12859017216.0000 - val_mse: 12859017216.0000
Epoch 3/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 13007741952.0000 - mse: 13007741952.0000 - val_loss: 12428672000.0000 - val_mse: 12428672000.0000
Epoch 4/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 12401899520.0000 - mse: 12401899520.0000 - val_loss: 11670054912.0000 - val_mse: 11670054912.0000
Epoch 5/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 11458924544.0000 - mse: 11458924544.0000 - val_loss: 10596088832.0000 - val_mse: 10596088832.0000
Epoch 6/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 10225598464.0000 - mse: 10225598464.0000 - val_loss: 9286884352.0000 - val_mse: 9286884352.0000
Epoch 7/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 8811917312.0000 - mse: 8811917312.0000 - val_loss: 7877648384.0000 - val_mse: 7877648384.0000
Epoch 8/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 7374149120.0000 - mse: 7374149120.0000 - val_loss: 6530461696.0000 - val_mse: 6530461696.0000
Epoch 9/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 6071362048.0000 - mse: 6071362048.0000 - val_loss: 5390818304.0000 - val_mse: 5390818304.0000
Epoch 10/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 5030648320.0000 - mse: 5030648320.0000 - val_loss: 4552506368.0000 - val_mse: 4552506368.0000
Epoch 11/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 4300496896.0000 - mse: 4300496896.0000 - val_loss: 4016878336.0000 - val_mse: 4016878336.0000
Epoch 12/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 3857201152.0000 - mse: 3857201152.0000 - val_loss: 3725083904.0000 - val_mse: 3725083904.0000
Epoch 13/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 3624867840.0000 - mse: 3624867840.0000 - val_loss: 3588640256.0000 - val_mse: 3588640256.0000
Epoch 14/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 3515503616.0000 - mse: 3515503616.0000 - val_loss: 3530330880.0000 - val_mse: 3530330880.0000
Epoch 15/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 3465662720.0000 - mse: 3465662720.0000 - val_loss: 3503100928.0000 - val_mse: 3503100928.0000
Epoch 16/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 3439298816.0000 - mse: 3439298816.0000 - val_loss: 3485564416.0000 - val_mse: 3485564416.0000
Epoch 17/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 3422799616.0000 - mse: 3422799616.0000 - val_loss: 3471785728.0000 - val_mse: 3471785728.0000
Epoch 18/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 3409868288.0000 - mse: 3409868288.0000 - val_loss: 3459641088.0000 - val_mse: 3459641088.0000
Epoch 19/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 3399396096.0000 - mse: 3399396096.0000 - val_loss: 3448421120.0000 - val_mse: 3448421120.0000
Epoch 20/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 3390058752.0000 - mse: 3390058752.0000 - val_loss: 3439206912.0000 - val_mse: 3439206912.0000
Epoch 21/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 3382340864.0000 - mse: 3382340864.0000 - val_loss: 3430189056.0000 - val_mse: 3430189056.0000
Epoch 22/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 3375117056.0000 - mse: 3375117056.0000 - val_loss: 3422944512.0000 - val_mse: 3422944512.0000
Epoch 23/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 3368819968.0000 - mse: 3368819968.0000 - val_loss: 3415525888.0000 - val_mse: 3415525888.0000
Epoch 24/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 3363277568.0000 - mse: 3363277568.0000 - val_loss: 3409504000.0000 - val_mse: 3409504000.0000
Epoch 25/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 3357968896.0000 - mse: 3357968896.0000 - val_loss: 3404002816.0000 - val_mse: 3404002816.0000
Epoch 26/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 3353761792.0000 - mse: 3353761792.0000 - val_loss: 3398629632.0000 - val_mse: 3398629632.0000
Epoch 27/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 3349468672.0000 - mse: 3349468672.0000 - val_loss: 3393499904.0000 - val_mse: 3393499904.0000
Epoch 28/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 3345542400.0000 - mse: 3345542400.0000 - val_loss: 3390920704.0000 - val_mse: 3390920704.0000
Epoch 29/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 3342238464.0000 - mse: 3342238464.0000 - val_loss: 3387154432.0000 - val_mse: 3387154432.0000
Epoch 30/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 3339075840.0000 - mse: 3339075840.0000 - val_loss: 3383810304.0000 - val_mse: 3383810304.0000
Epoch 31/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 3336670464.0000 - mse: 3336670464.0000 - val_loss: 3380241664.0000 - val_mse: 3380241664.0000
Epoch 32/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 3333805824.0000 - mse: 3333805824.0000 - val_loss: 3377082880.0000 - val_mse: 3377082880.0000
Epoch 33/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 3331489280.0000 - mse: 3331489280.0000 - val_loss: 3375411200.0000 - val_mse: 3375411200.0000
Epoch 34/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 3329222400.0000 - mse: 3329222400.0000 - val_loss: 3372487680.0000 - val_mse: 3372487680.0000
Epoch 35/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 3327239424.0000 - mse: 3327239424.0000 - val_loss: 3369755392.0000 - val_mse: 3369755392.0000
Epoch 36/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 3325271296.0000 - mse: 3325271296.0000 - val_loss: 3369058560.0000 - val_mse: 3369058560.0000
Epoch 37/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 3323593472.0000 - mse: 3323593472.0000 - val_loss: 3366411008.0000 - val_mse: 3366411008.0000
Epoch 38/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 3322188288.0000 - mse: 3322188288.0000 - val_loss: 3365039872.0000 - val_mse: 3365039872.0000
Epoch 39/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - loss: 3320399616.0000 - mse: 3320399616.0000 - val_loss: 3364275712.0000 - val_mse: 3364275712.0000
Epoch 40/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 3319145216.0000 - mse: 3319145216.0000 - val_loss: 3362900992.0000 - val_mse: 3362900992.0000
Epoch 41/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 3317616640.0000 - mse: 3317616640.0000 - val_loss: 3361264896.0000 - val_mse: 3361264896.0000
Epoch 42/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 2s 8ms/step - loss: 3316433408.0000 - mse: 3316433408.0000 - val_loss: 3361581824.0000 - val_mse: 3361581824.0000
Epoch 43/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 2s 8ms/step - loss: 3315286784.0000 - mse: 3315286784.0000 - val_loss: 3358000128.0000 - val_mse: 3358000128.0000
Epoch 44/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 2s 8ms/step - loss: 3313980928.0000 - mse: 3313980928.0000 - val_loss: 3358691328.0000 - val_mse: 3358691328.0000
Epoch 45/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 2s 8ms/step - loss: 3313308160.0000 - mse: 3313308160.0000 - val_loss: 3357210624.0000 - val_mse: 3357210624.0000
Epoch 46/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 2s 8ms/step - loss: 3312045568.0000 - mse: 3312045568.0000 - val_loss: 3356965120.0000 - val_mse: 3356965120.0000
Epoch 47/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 2s 8ms/step - loss: 3311042048.0000 - mse: 3311042048.0000 - val_loss: 3355585792.0000 - val_mse: 3355585792.0000
Epoch 48/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 3s 9ms/step - loss: 3310359040.0000 - mse: 3310359040.0000 - val_loss: 3355473920.0000 - val_mse: 3355473920.0000
Epoch 49/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 2s 8ms/step - loss: 3309455616.0000 - mse: 3309455616.0000 - val_loss: 3355019520.0000 - val_mse: 3355019520.0000
Epoch 50/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 2s 9ms/step - loss: 3308785152.0000 - mse: 3308785152.0000 - val_loss: 3355089920.0000 - val_mse: 3355089920.0000
Epoch 51/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 2s 9ms/step - loss: 3308013312.0000 - mse: 3308013312.0000 - val_loss: 3353877760.0000 - val_mse: 3353877760.0000
Epoch 52/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 2s 8ms/step - loss: 3307069952.0000 - mse: 3307069952.0000 - val_loss: 3352657664.0000 - val_mse: 3352657664.0000
Epoch 53/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 2s 9ms/step - loss: 3306333440.0000 - mse: 3306333440.0000 - val_loss: 3352781568.0000 - val_mse: 3352781568.0000
Epoch 54/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 2s 9ms/step - loss: 3305740544.0000 - mse: 3305740544.0000 - val_loss: 3351864832.0000 - val_mse: 3351864832.0000
Epoch 55/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 2s 9ms/step - loss: 3305050112.0000 - mse: 3305050112.0000 - val_loss: 3352265984.0000 - val_mse: 3352265984.0000
Epoch 56/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 2s 9ms/step - loss: 3304282368.0000 - mse: 3304282368.0000 - val_loss: 3351461632.0000 - val_mse: 3351461632.0000
Epoch 57/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 2s 8ms/step - loss: 3303626240.0000 - mse: 3303626240.0000 - val_loss: 3350870016.0000 - val_mse: 3350870016.0000
Epoch 58/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 2s 8ms/step - loss: 3303298560.0000 - mse: 3303298560.0000 - val_loss: 3350069504.0000 - val_mse: 3350069504.0000
Epoch 59/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 2s 8ms/step - loss: 3302808320.0000 - mse: 3302808320.0000 - val_loss: 3349563648.0000 - val_mse: 3349563648.0000
Epoch 60/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 2s 8ms/step - loss: 3302198528.0000 - mse: 3302198528.0000 - val_loss: 3349312768.0000 - val_mse: 3349312768.0000
Epoch 61/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 2s 9ms/step - loss: 3301859328.0000 - mse: 3301859328.0000 - val_loss: 3349145344.0000 - val_mse: 3349145344.0000
Epoch 62/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 2s 8ms/step - loss: 3301047552.0000 - mse: 3301047552.0000 - val_loss: 3348681984.0000 - val_mse: 3348681984.0000
Epoch 63/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 2s 9ms/step - loss: 3300461056.0000 - mse: 3300461056.0000 - val_loss: 3348602368.0000 - val_mse: 3348602368.0000
Epoch 64/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 2s 9ms/step - loss: 3300144384.0000 - mse: 3300144384.0000 - val_loss: 3348312576.0000 - val_mse: 3348312576.0000
Epoch 65/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 2s 8ms/step - loss: 3299431680.0000 - mse: 3299431680.0000 - val_loss: 3348733184.0000 - val_mse: 3348733184.0000
Epoch 66/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 2s 10ms/step - loss: 3299356416.0000 - mse: 3299356416.0000 - val_loss: 3348781056.0000 - val_mse: 3348781056.0000
Epoch 67/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 2s 9ms/step - loss: 3298710016.0000 - mse: 3298710016.0000 - val_loss: 3348960768.0000 - val_mse: 3348960768.0000
Epoch 68/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 2s 9ms/step - loss: 3298346496.0000 - mse: 3298346496.0000 - val_loss: 3349000192.0000 - val_mse: 3349000192.0000
Epoch 69/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 2s 9ms/step - loss: 3297798400.0000 - mse: 3297798400.0000 - val_loss: 3349584640.0000 - val_mse: 3349584640.0000
Epoch 70/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 2s 9ms/step - loss: 3297138688.0000 - mse: 3297138688.0000 - val_loss: 3347761408.0000 - val_mse: 3347761408.0000
Epoch 71/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 2s 8ms/step - loss: 3296978176.0000 - mse: 3296978176.0000 - val_loss: 3348456192.0000 - val_mse: 3348456192.0000
Epoch 72/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 2s 8ms/step - loss: 3296574464.0000 - mse: 3296574464.0000 - val_loss: 3348482048.0000 - val_mse: 3348482048.0000
Epoch 73/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 3296303360.0000 - mse: 3296303360.0000 - val_loss: 3349668352.0000 - val_mse: 3349668352.0000
Epoch 74/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 3295667200.0000 - mse: 3295667200.0000 - val_loss: 3348416768.0000 - val_mse: 3348416768.0000
Epoch 75/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 3295381760.0000 - mse: 3295381760.0000 - val_loss: 3348560384.0000 - val_mse: 3348560384.0000
Epoch 76/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 3294930688.0000 - mse: 3294930688.0000 - val_loss: 3347994112.0000 - val_mse: 3347994112.0000
Epoch 77/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 3294321152.0000 - mse: 3294321152.0000 - val_loss: 3349369344.0000 - val_mse: 3349369344.0000
Epoch 78/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 3294475008.0000 - mse: 3294475008.0000 - val_loss: 3348801536.0000 - val_mse: 3348801536.0000
Epoch 79/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 3293938688.0000 - mse: 3293938688.0000 - val_loss: 3347632384.0000 - val_mse: 3347632384.0000
Epoch 80/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 3293558272.0000 - mse: 3293558272.0000 - val_loss: 3347786752.0000 - val_mse: 3347786752.0000
Epoch 81/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 3293419776.0000 - mse: 3293419776.0000 - val_loss: 3347597568.0000 - val_mse: 3347597568.0000
Epoch 82/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 3292888832.0000 - mse: 3292888832.0000 - val_loss: 3347858432.0000 - val_mse: 3347858432.0000
Epoch 83/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 3292865280.0000 - mse: 3292865280.0000 - val_loss: 3349404160.0000 - val_mse: 3349404160.0000
Epoch 84/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 3292611072.0000 - mse: 3292611072.0000 - val_loss: 3348478720.0000 - val_mse: 3348478720.0000
Epoch 85/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 3292101632.0000 - mse: 3292101632.0000 - val_loss: 3347860480.0000 - val_mse: 3347860480.0000
Epoch 86/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 3291778304.0000 - mse: 3291778304.0000 - val_loss: 3348549120.0000 - val_mse: 3348549120.0000
Epoch 87/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 3291723264.0000 - mse: 3291723264.0000 - val_loss: 3348737536.0000 - val_mse: 3348737536.0000
Epoch 88/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 3291234816.0000 - mse: 3291234816.0000 - val_loss: 3347273728.0000 - val_mse: 3347273728.0000
Epoch 89/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 3290890752.0000 - mse: 3290890752.0000 - val_loss: 3347334400.0000 - val_mse: 3347334400.0000
Epoch 90/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 3290531584.0000 - mse: 3290531584.0000 - val_loss: 3347956992.0000 - val_mse: 3347956992.0000
Epoch 91/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 3290163712.0000 - mse: 3290163712.0000 - val_loss: 3346710784.0000 - val_mse: 3346710784.0000
Epoch 92/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 3289854720.0000 - mse: 3289854720.0000 - val_loss: 3347495168.0000 - val_mse: 3347495168.0000
Epoch 93/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 3289744128.0000 - mse: 3289744128.0000 - val_loss: 3348707584.0000 - val_mse: 3348707584.0000
Epoch 94/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 3289485824.0000 - mse: 3289485824.0000 - val_loss: 3348094720.0000 - val_mse: 3348094720.0000
Epoch 95/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 3289073664.0000 - mse: 3289073664.0000 - val_loss: 3348279552.0000 - val_mse: 3348279552.0000
Epoch 96/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 3289167872.0000 - mse: 3289167872.0000 - val_loss: 3348419584.0000 - val_mse: 3348419584.0000
Epoch 97/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 3288441344.0000 - mse: 3288441344.0000 - val_loss: 3346742016.0000 - val_mse: 3346742016.0000
Epoch 98/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 3288408320.0000 - mse: 3288408320.0000 - val_loss: 3347890944.0000 - val_mse: 3347890944.0000
Epoch 99/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 3288423168.0000 - mse: 3288423168.0000 - val_loss: 3347099136.0000 - val_mse: 3347099136.0000
Epoch 100/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 3287747328.0000 - mse: 3287747328.0000 - val_loss: 3347306240.0000 - val_mse: 3347306240.0000

In [36]:
%load_ext tensorboard

In [41]:
%tensorboard --logdir Regression/logs/fit

Reusing TensorBoard on port 6006 (pid 17868), started 0:00:09 ago. (Use '!kill 17868' to kill it.)

In [42]:
test_loss,test_mae=model.evaluate(X_test,y_test)
print(f"Test MAE: {test_mae}")

63/63 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 3346710784.0000 - mse: 3346710784.0000
Test MAE: 3346710784.0

In [43]:
model.save("regression_model.h5")

WARNING:absl:You are saving your model as an HDF5 file via `model.save()` or `keras.saving.save_model(model)`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')` or `keras.saving.save_model(model, 'my_model.keras')`.